AMQP_URI: pyamqp://guest:guest@localhost
WEB_SERVER_ADDRESS: 0.0.0.0:4001
rpc_exchange: rpc_Userinfo1
max_workers: 1000
parent_calls_tracked: 10
LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  root:
    level: DEBUG
    handlers:
    - console
